version: 2
updates:
    - package-ecosystem: "gradle"
      directory: "/DroidMedia"
      schedule:
          interval: "daily"
      rebase-strategy: "disabled"
      open-pull-requests-limit: 15

    - package-ecosystem: "github-actions"
      directory: "/"
      target-branch: master
      schedule:
          interval: "daily"
      rebase-strategy: "disabled"
      open-pull-requests-limit: 15